#!/bin/sh

TAR_CMD=${TAR_CMD:-"tar -cJf"}
SUFFIX=${SUFFIX:-"tar.xz"}
BACKUPS=${BACKUPS:-$HOME}
PREFIX=${PREFIX:-"backup"}
DATEFMT=${DATEFMT:-"%Y-%m-%d_%H:%M"}

retstr=""

function make_backup() {
	local BACKUP_DIR=$1
	local F_NAME=$BACKUPS/$PREFIX-$(date +$DATEFMT)-$(basename $BACKUP_DIR).$SUFFIX
	if [ -f $F_NAME ]; then
		retstr="ERR: $F_NAME already exist"
		return -1
	else
		$TAR_CMD $F_NAME $BACKUP_DIR &> /dev/null
		retstr="OK: $F_NAME created"
		return 0
	fi
}

