- name: Установка /etc/motd на всех узлах группы servers
  hosts: servers
  tasks:
    - name: Установка motd на основе хостовых переменных.
      copy: 
        content: "{{ msg }}"
        dest: /etc/motd
